max-players=18
online-mode=false
whitelist=false
enforce-whitelist=false
whitelist-names=
motd=\u00a76\u00a7l\u2728 Servidor do Heitor Maydana \u2728\u00a7r\n\u00a7b\u00a7oVenha brincar com a gente! \u00a7d\u2665
server-name=Heitor Maydana
difficulty=easy
gamemode=survival
pvp=false
spawn-protection=16
allow-flight=true
allow-nether=true
announce-player-achievements=true
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
generate-structures=true
hardcore=false
force-gamemode=false
player-idle-timeout=0
view-distance=12
simulation-distance=10
enable-command-block=true
function-permission-level=2
op-permission-level=4
require-resource-pack=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true